
name: Tests

on: [ push ]

env:
  CI: true

jobs:

  ci-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        node-version: [ 14.x, 16.x ]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      name: Checkout Module
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v2
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: |
        npm install
        cd docs; npm install; cd ..

    - name: Run tests
      run: npm run test

    - name: Docs
      run: |
        cd docs; npm run make; cd ..
        git status
        git diff
        git diff-index --quiet HEAD -- docs || (echo "$(tput bold)$(tput setaf 4)Did you forget to rebuild the docs?   $ cd docs; npm run make$(tput sgr0)"; exit 1)
